"""HTML report generation for VulnScanner."""

from __future__ import annotations

from html import escape
from pathlib import Path

from scanner.core import ScanResult


HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>VulnScanner Report - {target}</title>
  <style>
    :root {{
      --bg: #0d1117;
      --surface: #161b22;
      --border: #30363d;
      --accent: #00d084;
      --accent2: #3fb7ff;
      --danger: #ff5c5c;
      --warn: #ffb020;
      --text: #e6edf3;
      --muted: #8b949e;
      --font: "Courier New", monospace;
    }}
    * {{ box-sizing: border-box; }}
    body {{ margin: 0; background: var(--bg); color: var(--text); font-family: var(--font); }}
    header {{ border-bottom: 1px solid var(--border); padding: 32px 48px; display: flex; justify-content: space-between; gap: 24px; align-items: flex-end; }}
    main {{ max-width: 1100px; margin: 0 auto; padding: 32px 48px; }}
    .logo {{ color: var(--accent); font-size: 28px; font-weight: 700; letter-spacing: .08em; }}
    .logo span {{ color: var(--text); }}
    .muted, .meta {{ color: var(--muted); }}
    .meta {{ text-align: right; font-size: 13px; line-height: 1.7; }}
    .meta strong {{ color: var(--text); }}
    .summary-grid {{ display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 16px; margin-bottom: 40px; }}
    .card {{ background: var(--surface); border: 1px solid var(--border); border-radius: 6px; padding: 18px 20px; }}
    .card-label {{ color: var(--muted); text-transform: uppercase; letter-spacing: .08em; font-size: 12px; margin-bottom: 8px; }}
    .card-value {{ font-size: 28px; font-weight: 700; }}
    .accent {{ color: var(--accent); }}
    .danger {{ color: var(--danger); }}
    .risk-CRITICAL {{ color: #ff2d55; }}
    .risk-HIGH {{ color: var(--danger); }}
    .risk-MEDIUM {{ color: var(--warn); }}
    .risk-LOW {{ color: var(--accent); }}
    h2 {{ color: var(--muted); font-size: 13px; text-transform: uppercase; letter-spacing: .12em; border-bottom: 1px solid var(--border); padding-bottom: 8px; margin: 0 0 16px; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 14px; margin-bottom: 40px; }}
    th, td {{ text-align: left; border-bottom: 1px solid var(--border); padding: 11px 14px; vertical-align: top; }}
    th {{ color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: .08em; }}
    .port, .cve-id, a {{ color: var(--accent2); }}
    .service-name {{ color: var(--accent); }}
    .version-info, .no-cve, .empty-state, .cve-desc, .cve-port {{ color: var(--muted); }}
    .cve-card {{ background: var(--surface); border: 1px solid var(--border); border-left-width: 4px; border-radius: 6px; padding: 16px; margin-bottom: 12px; }}
    .cve-card.CRITICAL {{ border-left-color: #ff2d55; }}
    .cve-card.HIGH {{ border-left-color: var(--danger); }}
    .cve-card.MEDIUM {{ border-left-color: var(--warn); }}
    .cve-card.LOW {{ border-left-color: var(--accent); }}
    .cve-card.UNKNOWN {{ border-left-color: var(--muted); }}
    .cve-header {{ display: flex; justify-content: space-between; gap: 16px; margin-bottom: 8px; }}
    .cve-score {{ font-size: 12px; color: var(--muted); }}
    .cve-desc {{ font-size: 13px; line-height: 1.55; margin-bottom: 8px; }}
    .cve-port {{ font-size: 12px; margin-top: 8px; }}
    footer {{ border-top: 1px solid var(--border); padding: 24px 48px; text-align: center; color: var(--muted); font-size: 12px; }}
    @media (max-width: 800px) {{
      header {{ display: block; padding: 24px; }}
      main {{ padding: 24px; }}
      .meta {{ text-align: left; margin-top: 16px; }}
      .summary-grid {{ grid-template-columns: repeat(2, minmax(0, 1fr)); }}
    }}
  </style>
</head>
<body>
  <header>
    <div>
      <div class="logo">VULN<span>SCANNER</span></div>
      <div class="muted">Vulnerability Assessment Report</div>
    </div>
    <div class="meta">
      <strong>Target:</strong> {target} ({ip})<br>
      <strong>Hostname:</strong> {hostname}<br>
      <strong>Scanned:</strong> {scan_time}<br>
      <strong>Generated by:</strong> VulnScanner v1.0
    </div>
  </header>
  <main>
    <div class="summary-grid">
      <div class="card"><div class="card-label">Open Ports</div><div class="card-value accent">{total_open}</div></div>
      <div class="card"><div class="card-label">CVEs Found</div><div class="card-value {cve_class}">{total_cves}</div></div>
      <div class="card"><div class="card-label">Risk Level</div><div class="card-value risk-{risk_level}">{risk_level}</div></div>
      <div class="card"><div class="card-label">Scan Date</div><div class="card-value">{scan_date}</div></div>
    </div>
    <section>
      <h2>Detected Services</h2>
      {services_table}
    </section>
    <section>
      <h2>CVE Details</h2>
      {cve_details}
    </section>
  </main>
  <footer>VulnScanner - For authorized testing only. Report generated: {scan_time}</footer>
</body>
</html>
"""


def _services_table(services) -> str:
    if not services:
        return '<p class="empty-state">No open ports found.</p>'

    rows = []
    for svc in services:
        product_ver = " ".join(filter(None, [svc.product, svc.version, svc.extrainfo]))
        cve_badge = (
            f'<span style="color:var(--warn)">{len(svc.cves)} CVE(s)</span>'
            if svc.cves
            else '<span class="no-cve">None found</span>'
        )
        rows.append(
            "<tr>"
            f'<td class="port">{svc.port}/{escape(str(svc.protocol))}</td>'
            f'<td class="service-name">{escape(str(svc.name))}</td>'
            f'<td><span class="version-info">{escape(product_ver) if product_ver else "-"}</span></td>'
            f"<td>{cve_badge}</td>"
            "</tr>"
        )

    return (
        "<table>"
        "<thead><tr><th>Port</th><th>Service</th><th>Version</th><th>CVEs</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody>"
        "</table>"
    )


def _cve_details(services) -> str:
    all_cves = [(svc, cve) for svc in services for cve in svc.cves]
    if not all_cves:
        return '<p class="empty-state">No CVEs found for detected services.</p>'

    all_cves.sort(key=lambda item: item[1].get("cvss_score") or 0, reverse=True)
    cards = []
    for svc, cve in all_cves:
        severity = escape(str(cve.get("severity", "UNKNOWN")))
        score = cve.get("cvss_score")
        score_label = f"CVSS {score}" if score else "No score"
        cards.append(
            f'<div class="cve-card {severity}">'
            '<div class="cve-header">'
            f'<span class="cve-id">{escape(str(cve["id"]))}</span>'
            f'<span class="cve-score">{escape(score_label)} - {severity}</span>'
            "</div>"
            f'<div class="cve-desc">{escape(str(cve["description"]))}</div>'
            f'<a href="{escape(str(cve["url"]), quote=True)}" target="_blank">View on NVD</a>'
            f'<div class="cve-port">Affects: port {svc.port}/{escape(str(svc.protocol))} '
            f'({escape(str(svc.name))} {escape(str(svc.product))} {escape(str(svc.version))})</div>'
            "</div>"
        )
    return "".join(cards)


def generate_html(result: ScanResult, output_path: str) -> str:
    """Generate an HTML report and return the output path."""
    scan_date = str(result.scan_time).split(" ")[0]
    html = HTML_TEMPLATE.format(
        target=escape(str(result.target)),
        ip=escape(str(result.ip)),
        hostname=escape(str(result.hostname)),
        scan_time=escape(str(result.scan_time)),
        scan_date=escape(scan_date),
        total_open=result.total_open,
        total_cves=result.total_cves,
        risk_level=escape(str(result.risk_level)),
        cve_class="danger" if result.total_cves > 0 else "accent",
        services_table=_services_table(result.services),
        cve_details=_cve_details(result.services),
    )
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(html, encoding="utf-8")
    return output_path
